//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Structured_Programming.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int ItemId { get; set; }
        public int TypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Trade { get; set; }
        public int UserId { get; set; }
    
        public virtual Type Type { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
