//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Structured_Programming.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Item
    {
        [Key]
        public int ItemId { get; set; }
        public int TypeId { get; set; }
        [Required]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }

        [Display(Name = "Price")]
        public Nullable<decimal> Price { get; set; }

        [Display(Name = "Want to trade with")]
        public string Trade { get; set; }

        [Required]
        [Display(Name = "Type")]
        public int UserId { get; set; }
    
        public virtual Type Type { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
