//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Structured_Programming.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public int BuyerId { get; set; }
        public int ItemId { get; set; }
        public string Message { get; set; }
        public decimal Pay { get; set; }
        public int MethodId { get; set; }
        public int StatusId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual Method Method { get; set; }
        public virtual Status Status { get; set; }
    }
}
